title: CV | A jekyll template
description:  A beautiful template for your CV.
url: https://stavrospanakakis.github.io
baseurl: '/jekyll-cv'
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
